services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  app:
    build: .
    environment:
      MONGODB_URI: mongodb://mongo:27017/blackjack
      R2DBC_URL: r2dbc:pool:mysql://mysql:3306/blackjack
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
