spring:
  application:
    name: blackjack-reactive-api

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/blackjack}
  r2dbc:
    url: ${R2DBC_URL:r2dbc:pool:mysql://mysql:3306/blackjack}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  codec:
    max-in-memory-size: 10MB

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
