spring:
  application:
    name: blackjack-reactive-api

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/blackjack}

  r2dbc:
    url: ${R2DBC_URL:r2dbc:pool:mysql://${MYSQL_HOST:localhost}:3306/blackjack}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  codec:
    max-in-memory-size: 10MB

  flyway:
    enabled: true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:blackjack}
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
